<?php if (defined('AAM_CONFIGPRESS')) { ?>
    <div class="aam-feature" id="configpress-content">
        <div class="row">
            <div class="col-xs-12">
                <p class="aam-info">
                    Fore more information about AAM configurations check <a href="https://aamplugin.com/help/aam-configurations">this article</a>
                </p>
            </div>
        </div>
        
        <textarea id="configpress" class="configpress-editor" rows="10"><?php echo $this->getConfig(); ?></textarea>
    </div>
<?php }